server:
  port: 8011
eureka:
  instance:
    hostname: localhost
    status-page-url-path: ${management.contextPath}/info
    health-check-url-path: ${management.contextPath}/health
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/