---
spring:
 cloud:
   config:
     server:
       git :
         uri: https://github.com/manoj493/feo
         searchPaths: configdata
 application:
    name: configserver
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8011/eureka/