---
spring:
 cloud:
   config:
     server:
       git :
         uri: https://github.com/manoj493/feo
         #uri: https://github.com/spring-cloud-samples/config-repo
         searchPaths: configdata
 application:
    name: configserver
server:
  port: 8001
